---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongosh2-pv-1
  labels:
    pv: mongosh2-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  glusterfs:
    endpoints: "mongo2-1"
    path: "mongo2-1"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongosh2-pvc-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: mongosh2-pv-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongosh2-pv-2
  labels:
    pv: mongosh2-pv-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  glusterfs:
    endpoints: "mongo2-2"
    path: "mongo2-2"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongosh2-pvc-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: mongosh2-pv-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongosh2-pv-3
  labels:
    pv: mongosh2-pv-3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  glusterfs:
    endpoints: "mongo2-3"
    path: "mongo2-3"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongosh2-pvc-3
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: mongosh2-pv-3
---
apiVersion: v1
kind: Service
metadata:
  name: mongosh2-1
  labels:
    run: mongosh2-1
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    run: mongosh2-1
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongosh2-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongosh2-1
        run: mongosh2-1
    spec:
      restartPolicy: Always
      hostname: mongosh2-1
      containers:
      - image: mongo:latest
        name: mongosh2-1
        ports:
        - name: mongosh2-1
          containerPort: 27017
        volumeMounts:
          - name: mongosh2-1
            mountPath: /mongosh2-1/db
          - name: keyfile
            mountPath: "/data/keyfile"
            readOnly: true
        command: ["mongod"]
        args: ["--noprealloc", "--smallfiles", "--shardsvr", "--replSet", "rs2", "--dbpath","/mongosh2-1/db", "--port", "27017", "--bind_ip_all", "--keyFile", "/data/keyfile/keyfile"]
      volumes:
        - name: keyfile
          secret:
            secretName: keyfile
            defaultMode: 0400
        - name: mongosh2-1
          persistentVolumeClaim:
           claimName: mongosh2-pvc-1
---
# Mongo shard replica set 1 node 2
apiVersion: v1
kind: Service
metadata:
  name: mongosh2-2
  labels:
    run: mongosh2-2
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    run: mongosh2-2
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongosh2-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongosh2-2
        run: mongosh2-2
    spec:
      restartPolicy: Always
      hostname: mongosh2-2
      containers:
      - image: mongo:latest
        name: mongosh2-2
        ports:
        - name: mongosh2-2
          containerPort: 27017
        volumeMounts:
          - name: mongosh2-2
            mountPath: /mongosh2-2/db
          - name: keyfile
            mountPath: "/data/keyfile"
            readOnly: true
        command: ["mongod"]
        args: ["--noprealloc", "--smallfiles", "--shardsvr", "--replSet", "rs2", "--dbpath","/mongosh2-2/db", "--port", "27017", "--bind_ip_all", "--keyFile", "/data/keyfile/keyfile"]
      volumes:
        - name: keyfile
          secret:
            secretName: keyfile
            defaultMode: 0400
        - name: mongosh2-2
          persistentVolumeClaim:
           claimName: mongosh2-pvc-2
---
# Mongo shard replica set 1 node 1
apiVersion: v1
kind: Service
metadata:
  name: mongosh2-3
  labels:
    run: mongosh2-3
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    run: mongosh2-3
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongosh2-3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongosh2-3
        run: mongosh2-3
    spec:
      restartPolicy: Always
      hostname: mongosh2-3
      containers:
      - image: mongo:latest
        name: mongosh2-3
        ports:
        - name: mongosh2-3
          containerPort: 27017
        volumeMounts:
          - name: mongosh2-3
            mountPath: /mongosh2-3/db
          - name: keyfile
            mountPath: "/data/keyfile"
            readOnly: true
        command: ["mongod"]
        args: ["--noprealloc", "--smallfiles", "--shardsvr", "--replSet", "rs2", "--dbpath","/mongosh2-3/db", "--port", "27017", "--bind_ip_all", "--keyFile", "/data/keyfile/keyfile"]
      volumes:
        - name: keyfile
          secret:
            secretName: keyfile
            defaultMode: 0400
        - name: mongosh2-3
          persistentVolumeClaim:
           claimName: mongosh2-pvc-3
